http:
  port: 8080

apiEndpoints:
  user_signup:
    path: /api/signup
    method: POST

  user_login:
    path: /api/login
    method: POST

  movie_getAll:
    path: /api/movies
    method: GET

  movie_getById:
    path: /api/movies/:id
    method: GET

  movie_add:
    path: /api/movies
    method: POST

  movie_update:
    path: /api/movies/:id
    method: PUT

  movie_delete:
    path: /api/movies/:id
    method: DELETE

  movie_static_files:
    path: /uploads/*
    method: GET

serviceEndpoints:
  user-service:
    url: http://localhost:5000
  movie-service:
    url: http://localhost:5001

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy

pipelines:
  user:
    apiEndpoints:
      - user_signup
      - user_login
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service

  movies:
    apiEndpoints:
      - movie_getAll
      - movie_getById
      - movie_add
      - movie_update
      - movie_delete
      - movie_static_files
    policies:
      - proxy:
          - action:
              serviceEndpoint: movie-service
