http:
  port: 8080

apiEndpoints:
  user_signup:
    path: /api/signup
    method: POST

  user_login:
    path: /api/login
    method: POST

  movie_getAll:
    path: /api/movies
    method: GET

  movie_getById:
    path: /api/movies/:id
    method: GET

  movie_add:
    path: /api/movies
    method: POST

  movie_update:
    path: /api/movies/:id
    method: PUT

  movie_delete:
    path: /api/movies/:id
    method: DELETE

  movie_static_files:
    path: /movies/uploads/*
    method: GET

  theater_getAll:
    path: /api/theaters
    method: GET

  theater_getById:
    path: /api/theaters/:id
    method: GET

  theater_create:
    path: /api/theaters
    method: POST

  theater_update:
    path: /api/theaters/:id
    method: PUT

  theater_delete:
    path: /api/theaters/:id
    method: DELETE

  theater_getGallery:
    path: /api/theaters/:id/gallery
    method: GET

  theater_static_files:
    path: /theaters/uploads/*
    method: GET

  room_create:
    path: /api/rooms
    method: POST

  room_edit:
    path: /api/rooms/:roomId
    method: PUT

  room_delete:
    path: /api/rooms/:roomId
    method: DELETE

  seats_create:
    path: /api/seats/generate
    method: POST

  seats_room:
    path: /api/seats/room/:roomId
    method: GET

  seats_type:
    path: /api/seats/:seatId/type
    method: PUT

  seats_status:
    path: /api/seats/:seatId/status
    method: PUT

  room_getAllByTheater:
    path: /api/rooms/theater/:theaterId
    method: GET

serviceEndpoints:
  user-service:
    url: http://localhost:5000
  movie-service:
    url: http://localhost:5001
  theater-service:
    url: http://localhost:5002  

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy

pipelines:
  user:
    apiEndpoints:
      - user_signup
      - user_login
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service

  movies:
    apiEndpoints:
      - movie_getAll
      - movie_getById
      - movie_add
      - movie_update
      - movie_delete
      - movie_static_files
    policies:
      - proxy:
          - action:
              serviceEndpoint: movie-service
    
  theaters:
    apiEndpoints:
      - theater_getAll
      - theater_getById
      - theater_create
      - theater_update
      - theater_delete
      - theater_getGallery
      - theater_static_files
      - room_create        
      - room_edit
      - room_delete     
      - room_getAllByTheater
      - seats_create
      - seats_room
      - seats_type
      - seats_status

    policies:
      - proxy:
          - action:
              serviceEndpoint: theater-service