http:
  port: 8080

apiEndpoints:
  user_signup:
    path: /api/signup
    method: POST
  user_login:
    path: /api/login
    method: POST

serviceEndpoints:
  user-service:
    url: http://localhost:5000

policies:             
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
pipelines:
  user:
    apiEndpoints:
      - user_signup
      - user_login
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service
