http:
  port: 8080

apiEndpoints:
  user_signup:
    path: /api/signup
    method: POST

  user_login:
    path: /api/login
    method: POST

  user_getAll:
    path: /api/users
    method: GET

  user_get:
    path: /api/users/:id
    method: GET

  user_update:
    path: /api/users/:id
    method: PUT

  user_change_password:
    path: /api/users/:id/change-password
    method: PUT

  user_send_otp:
    path: /api/forgot-password/send-otp
    method: POST

  user_verify_otp:
    path: /api/forgot-password/verify-otp
    method: POST

  user_reset_password:
    path: /api/forgot-password/reset-password
    method: POST

  employee_create:
    path: /api/employees
    method: POST

  employee_update:
    path: /api/employees/:id
    method: PUT

  employee_delete:
    path: /api/employees/:id
    method: DELETE

  employee_getAll:
    path: /api/employees/
    method: GET

  movie_getAll:
    path: /api/movies
    method: GET

  movie_getById:
    path: /api/movies/:id
    method: GET

  movie_add:
    path: /api/movies
    method: POST

  movie_update:
    path: /api/movies/:id
    method: PUT

  movie_delete:
    path: /api/movies/:id
    method: DELETE

  movie_static_files:
    path: /movies/uploads/*
    method: GET

  theater_getAll:
    path: /api/theaters
    method: GET

  theater_getById:
    path: /api/theaters/:id
    method: GET

  theater_create:
    path: /api/theaters
    method: POST

  theater_update:
    path: /api/theaters/:id
    method: PUT

  theater_delete:
    path: /api/theaters/:id
    method: DELETE

  theater_getGallery:
    path: /api/theaters/:id/gallery
    method: GET

  theater_static_files:
    path: /theaters/uploads/*
    method: GET

  room_create:
    path: /api/rooms
    method: POST

  room_edit:
    path: /api/rooms/:roomId
    method: PUT

  room_delete:
    path: /api/rooms/:roomId
    method: DELETE

  seats_create:
    path: /api/seats/generate
    method: POST

  seats_get:
    path: /api/seats/:seatId
    method: GET
  seats_room:
    path: /api/seats/room/:roomId
    method: GET

  seats_type:
    path: /api/seats/:seatId/type
    method: PUT

  seats_status:
    path: /api/seats/:seatId/status
    method: PUT

  room_getAllByTheater:
    path: /api/rooms/theater/:theaterId
    method: GET

  showtime_create:
    path: /api/showtimes
    method: POST

  showtime_get:
    path: /api/showtimes
    method: GET

  showtime_getId:
    path: /api/showtimes/:showtimeId
    method: GET

  showtime_delete:
    path: /api/showtimes/:showtimeId
    method: DELETE

  booking_getAll:
    path: /api/bookings
    method: GET

  booking_getByUser:
    path: /api/bookings/user/:userId
    method: GET

  booking_getById:
    path: /api/bookings/:id
    method: GET

  booking_create:
    path: /api/bookings
    method: POST

  booking_updatePrice:
    path: /api/bookings/:id/total_price
    method: PUT

  booking_updateStatus:
    path: /api/bookings/:id/status
    method: PUT

  booking_delete:
    path: /api/bookings/:id
    method: DELETE

  booking_lockedSeats:
    path: /api/bookings/locked-seats/:showtimeId
    method: GET

  booking_refund_request:
    path: /api/bookings/:id/refund-request
    method: POST

  booking_refund_cancel:
    path: /api/bookings/:id/refund-cancel
    method: DELETE

  booking_refund_booking:
    path: /api/bookings/refund-bookings/booking/:bookingId
    method: GET

  booking_refund_bookingId:
    path: /api/bookings/refund-bookings/:id
    method: GET

  refund_booking_getAll:
    path: /api/bookings/refund-bookings
    method: GET

  food_booking_getAll:
    path: /api/food-bookings
    method: GET

  food_booking_getByUser:
    path: /api/food-bookings/user/:userId
    method: GET

  food_booking_getById:
    path: /api/food-bookings/:id
    method: GET

  food_booking_create:
    path: /api/food-bookings
    method: POST

  food_booking_updatePrice:
    path: /api/food-bookings/:id/total_price
    method: PUT

  food_booking_updateStatus:
    path: /api/food-bookings/:id/status
    method: PUT

  food_booking_delete:
    path: /api/food-bookings/:id
    method: DELETE

  food_booking_getItemsByBookingId:
    path: /api/food-bookings/:id/items
    method: GET

  payment_payos:
    path: /api/payments/payos
    method: POST

  payment_success:
    path: /api/payments/success
    method: POST

  food_getAll:
    path: /api/foods
    method: GET

  food_getById:
    path: /api/foods/:id
    method: GET

  food_add:
    path: /api/foods
    method: POST

  food_update:
    path: /api/foods/:id
    method: PUT

  food_delete:
    path: /api/foods/:id
    method: DELETE

  food_static_files:
    path: /foods/uploads/*
    method: GET

  promotion_getAll:
    path: /api/promotions
    method: GET

  promotion_getById:
    path: /api/promotions/:id
    method: GET

  promotion_add:
    path: /api/promotions
    method: POST

  promotion_update:
    path: /api/promotions/:id
    method: PUT

  promotion_delete:
    path: /api/promotions/:id
    method: DELETE

  promotion_static_files:
    path: /promotions/uploads/*
    method: GET

serviceEndpoints:
  user-service:
    url: http://localhost:5000
  movie-service:
    url: https://movieservice-gwdb.onrender.com
  theater-service:
    url: http://localhost:5002
  schedule-service:
    url: http://localhost:5003
  booking-service:
    url: http://localhost:5006
  payment-service:
    url: http://localhost:5005
  food-service:
    url: http://localhost:5007
  promotion-service:
    url: http://localhost:5008

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy

pipelines:
  user:
    apiEndpoints:
      - user_signup
      - user_login
      - user_getAll
      - user_get
      - user_update
      - user_change_password
      - user_send_otp
      - user_verify_otp
      - user_reset_password
      - employee_create
      - employee_update
      - employee_delete
      - employee_getAll
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service

  movies:
    apiEndpoints:
      - movie_getAll
      - movie_getById
      - movie_add
      - movie_update
      - movie_delete
      - movie_static_files
    policies:
      - proxy:
          - action:
              serviceEndpoint: movie-service

  foods:
    apiEndpoints:
      - food_getAll
      - food_getById
      - food_add
      - food_update
      - food_delete
      - food_static_files
    policies:
      - proxy:
          - action:
              serviceEndpoint: food-service

  theaters:
    apiEndpoints:
      - theater_getAll
      - theater_getById
      - theater_create
      - theater_update
      - theater_delete
      - theater_getGallery
      - theater_static_files
      - room_create
      - room_edit
      - room_delete
      - room_getAllByTheater
      - seats_create
      - seats_get
      - seats_room
      - seats_type
      - seats_status

    policies:
      - proxy:
          - action:
              serviceEndpoint: theater-service

  showtimes:
    apiEndpoints:
      - showtime_create
      - showtime_get
      - showtime_getId
      - showtime_delete

    policies:
      - proxy:
          - action:
              serviceEndpoint: schedule-service

  bookings:
    apiEndpoints:
      - booking_getAll
      - booking_getById
      - booking_getByUser
      - booking_create
      - booking_updatePrice
      - booking_updateStatus
      - booking_delete
      - booking_lockedSeats
      - booking_refund_request
      - booking_refund_cancel
      - booking_refund_booking
      - booking_refund_bookingId
      - refund_booking_getAll
      - food_booking_getAll
      - food_booking_getById
      - food_booking_getByUser
      - food_booking_create
      - food_booking_updatePrice
      - food_booking_updateStatus
      - food_booking_delete
      - food_booking_getItemsByBookingId

    policies:
      - proxy:
          - action:
              serviceEndpoint: booking-service

  payments:
    apiEndpoints:
      - payment_payos
      - payment_success
    policies:
      - proxy:
          - action:
              serviceEndpoint: payment-service

  promotions:
    apiEndpoints:
      - promotion_getAll
      - promotion_getById
      - promotion_add
      - promotion_update
      - promotion_delete
      - promotion_static_files
    policies:
      - proxy:
          - action:
              serviceEndpoint: promotion-service
